- hosts: all
  user: "{{ user_name }}"
  serial: 3
  gather_facts: False

  tasks:
  - name: "User on remote machine: {{ user_name }}"
    command: whoami
    register: currentuser
    changed_when: False

  - debug: msg="{{currentuser.stdout}}"

  - name: "Privileged user on remote machine: {{ ansible_become_user }}"
    command: whoami
    register: currentuser
    changed_when: False
    become: True

  - debug: msg="{{currentuser.stdout}}"
